/**
 * Paints the docs site from the house preset.
 *
 * `apps/web` used to carry a hand-transcribed copy of the library's neutral
 * palette on Fumadocs' `--color-fd-*` names. It now reads `HOUSE_CONFIG` from
 * `@delacour/design-system/house` — the studio's own theme, composed on the
 * same seven axes `/theme` sells — resolves it with `resolveTokens`, and writes
 * two committed files:
 *
 * - `src/styles/house.css`: a Tailwind `@theme` block (light) and a `.dark`
 *   block, mapping the library's token names onto Fumadocs' slots, plus the
 *   three faces and the radius.
 * - `src/lib/house-meta.ts`: the two page backgrounds as sRGB hex, for the
 *   `theme-color` metas and the web manifest, which cannot read `oklch()`.
 *
 * Both are generated rather than imported at runtime so the palette is in the
 * CSS the browser fetches first, with no client work and no flash — and so
 * `app.css.test.ts` can hold the committed file equal to a fresh render, the
 * way `emit.test.ts` holds the emitter to `tokens.css`.
 *
 * Regenerate with `bun run gen-theme` from `apps/web`.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { HOUSE_CONFIG, HOUSE_PRESET_CODE } from "@delacour/design-system/house";
import { type ResolvedMode, resolveFonts, resolveTokens } from "@delacour/design-system/resolve";
import { houseFonts } from "../src/lib/house";

const WEB = join(import.meta.dirname, "..");
const CSS_OUT = join(WEB, "src", "styles", "house.css");
const META_OUT = join(WEB, "src", "lib", "house-meta.ts");

/**
 * Fumadocs slot ← library token.
 *
 * `fd-card` maps to `card` outright. The old transcription substituted
 * `tertiary` because the neutral base's `card` and `background` were the same
 * white; zinc's are not (`card` is white on a `0.985` page), so a docs card
 * reads as a surface in light mode without a special case.
 *
 * `fd-error` is the only status slot mapped: `resolveTokens` carries
 * `destructive` and no `success` / `warning` / `info` — those are derived by
 * `convertTheme` on the way into a native `theme.css`, not composed by an
 * axis — so Fumadocs' own values for the other three stand.
 */
export const MAPPING: readonly (readonly [slot: string, token: string])[] = [
	["fd-background", "background"],
	["fd-foreground", "foreground"],
	["fd-muted", "muted"],
	["fd-muted-foreground", "muted-foreground"],
	["fd-popover", "popover"],
	["fd-popover-foreground", "popover-foreground"],
	["fd-card", "card"],
	["fd-card-foreground", "card-foreground"],
	["fd-border", "border"],
	["fd-primary", "primary"],
	["fd-primary-foreground", "primary-foreground"],
	["fd-secondary", "secondary"],
	["fd-secondary-foreground", "secondary-foreground"],
	["fd-accent", "accent"],
	["fd-accent-foreground", "accent-foreground"],
	["fd-ring", "ring"],
	["fd-error", "destructive"],
];

/** After the chosen family, somewhere to go while the webfont loads. */
export const SANS_FALLBACK = "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif";
export const MONO_FALLBACK = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

const HEADER = `/*
 * Generated by apps/web/scripts/gen-theme.ts from HOUSE_CONFIG
 * (@delacour/design-system/house, preset ${HOUSE_PRESET_CODE}). Do not edit.
 *
 * Regenerate with \`bun run gen-theme\` from apps/web. \`app.css.test.ts\` holds
 * this file equal to a fresh render.
 */`;

function colour(mode: ResolvedMode, token: string): string {
	const value = mode[token];
	if (value === undefined) throw new Error(`resolveTokens wrote no "${token}"`);
	return String(value);
}

function radiusRem(mode: ResolvedMode): string {
	const value = mode.radius;
	if (typeof value !== "number") throw new Error("resolveTokens wrote no numeric radius");
	return `${Math.round((value / 16) * 1e6) / 1e6}rem`;
}

function quoted(family: string): string {
	return family.includes(" ") ? `"${family}"` : family;
}

/** The three `--font-*` declarations, from the resolved families. */
export function fontDeclarations(): readonly (readonly [name: string, value: string])[] {
	const { sans, heading } = resolveFonts(HOUSE_CONFIG);
	const mono = houseFonts().find((font) => font.type === "mono")?.family;
	if (!sans || !heading || !mono) throw new Error("the house preset must name a sans, a heading and a mono face");

	return [
		["--font-sans", `${quoted(sans)}, ${SANS_FALLBACK}`],
		["--font-heading", `${quoted(heading)}, ${SANS_FALLBACK}`],
		["--font-mono", `${quoted(mono)}, ${MONO_FALLBACK}`],
	];
}

function paletteLines(mode: ResolvedMode): string {
	return MAPPING.map(([slot, token]) => `\t--color-${slot}: ${colour(mode, token)};`).join("\n");
}

/**
 * `house.css`, whole.
 *
 * `--color-capture` is the page background every preview under
 * `public/previews/` was photographed on. `bun run previews` forces
 * `HOUSE_CONFIG` on the capture route, so today it is the house page itself;
 * it keeps its own name so a frame is painted from what the media was shot on
 * rather than from whatever the page happens to be, and the two cannot drift
 * apart without this line changing.
 */
export function renderHouseCss(): string {
	const { light, dark } = resolveTokens(HOUSE_CONFIG);
	const captured = resolveTokens(HOUSE_CONFIG);
	const fonts = fontDeclarations()
		.map(([name, value]) => `\t${name}: ${value};`)
		.join("\n");

	return `${HEADER}

@theme {
${paletteLines(light)}

	--color-capture: ${colour(captured.light, "background")};

${fonts}

	--radius: ${radiusRem(light)};
}

.dark {
${paletteLines(dark)}

	--color-capture: ${colour(captured.dark, "background")};
}
`;
}

/**
 * `oklch()` to `#rrggbb`.
 *
 * The three matrices are Björn Ottosson's own, the same ones the library's
 * `culori` dependency carries. Written here rather than imported so this script
 * — and the test that reruns it — depend on nothing the app does not already.
 * Chroma is clipped to the sRGB gamut by clamping, which is what a browser does
 * for these near-neutral values too.
 */
export function oklchToHex(value: string): string {
	const match = /^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*[\d.]+%?\s*)?\)$/.exec(value.trim());
	if (!match) throw new Error(`not an oklch() colour: "${value}"`);

	const L = Number(match[1]);
	const C = Number(match[2]);
	const h = (Number(match[3]) * Math.PI) / 180;
	const a = C * Math.cos(h);
	const b = C * Math.sin(h);

	const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
	const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
	const s_ = L - 0.0894841775 * a - 1.291485548 * b;

	const l = l_ ** 3;
	const m = m_ ** 3;
	const s = s_ ** 3;

	const linear = [
		4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
		-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
		-0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
	];

	const channel = (c: number): string => {
		const clamped = Math.min(1, Math.max(0, c));
		const gamma = clamped <= 0.0031308 ? 12.92 * clamped : 1.055 * clamped ** (1 / 2.4) - 0.055;
		return Math.round(gamma * 255)
			.toString(16)
			.padStart(2, "0");
	};

	return `#${linear.map(channel).join("")}`;
}

export type HouseMeta = { readonly light: string; readonly dark: string };

/** The two page backgrounds as hex — what `theme-color` and the manifest take. */
export function houseMeta(): HouseMeta {
	const { light, dark } = resolveTokens(HOUSE_CONFIG);
	return { light: oklchToHex(colour(light, "background")), dark: oklchToHex(colour(dark, "background")) };
}

/** `house-meta.ts`, whole. */
export function renderHouseMeta(): string {
	const meta = houseMeta();

	return `// Generated by apps/web/scripts/gen-theme.ts from HOUSE_CONFIG. Do not edit.
//
// The house page backgrounds as sRGB hex — \`--color-fd-background\` in each
// mode, for the two places that cannot read \`oklch()\`: the \`theme-color\`
// metas and the web manifest. Regenerate with \`bun run gen-theme\`.

/** The house preset's page background, light and dark, as \`#rrggbb\`. */
export const HOUSE_BACKGROUND = {
	light: "${meta.light}",
	dark: "${meta.dark}",
} as const;
`;
}

if (import.meta.main) {
	writeFileSync(CSS_OUT, renderHouseCss());
	console.log(`Wrote ${CSS_OUT}`);
	writeFileSync(META_OUT, renderHouseMeta());
	console.log(`Wrote ${META_OUT}`);
}
