/**
 * Emits `apps/web/src/previews/manifest.ts` — the contract between the capture
 * run and the documentation site.
 *
 * A `.ts` module rather than JSON, because JSON widens every key to `string`
 * and the point of the file is that `<Preview id="switch/colours" />` is a
 * literal union a rename cannot silently break.
 */

export type PreviewMediaJson = {
	poster: string;
	video?: string;
};

export type PreviewEntryJson = {
	id: string;
	component: string;
	demo: string;
	title: string;
	description?: string;
	frame: "stage" | "device";
	width: number;
	height: number;
	animated: boolean;
	durationMs?: number;
	light: PreviewMediaJson;
	dark: PreviewMediaJson;
	sourceHash: string;
	capturedAt: string;
	device: string;
};

const HEADER = `// Generated by apps/playground/scripts/capture-previews.ts. Do not edit.
//
// Regenerate with \`bun run previews\` from the repo root. A demo whose source
// is unchanged is skipped, so a run after touching one component rewrites that
// component's entries and nothing else.

export type PreviewFrame = "stage" | "device";

export type PreviewMedia = {
	/** Site-absolute and cache-busted: Vite copies \`public/\` with no content hashing. */
	readonly poster: string;
	/** Absent on a static demo. */
	readonly video?: string;
};

export type PreviewEntry = {
	readonly id: string;
	readonly component: string;
	readonly demo: string;
	readonly title: string;
	readonly description?: string;
	readonly frame: PreviewFrame;
	/** Intrinsic pixels of the encoded media, so the page reserves the right box. */
	readonly width: number;
	readonly height: number;
	readonly animated: boolean;
	readonly durationMs?: number;
	readonly light: PreviewMedia;
	readonly dark: PreviewMedia;
	/** sha256 of the demo source and its capture settings. Drives the skip, and the cache-buster. */
	readonly sourceHash: string;
	readonly capturedAt: string;
	readonly device: string;
};
`;

/** `JSON.stringify` produces a valid TS string literal, escapes and all. */
function literal(value: string): string {
	return JSON.stringify(value);
}

function renderMedia(media: PreviewMediaJson): string {
	const video = media.video ? `, video: ${literal(media.video)}` : "";
	return `{ poster: ${literal(media.poster)}${video} }`;
}

function renderEntry(entry: PreviewEntryJson): string {
	const lines = [
		`\t\tid: ${literal(entry.id)},`,
		`\t\tcomponent: ${literal(entry.component)},`,
		`\t\tdemo: ${literal(entry.demo)},`,
		`\t\ttitle: ${literal(entry.title)},`,
		entry.description ? `\t\tdescription: ${literal(entry.description)},` : null,
		`\t\tframe: ${literal(entry.frame)},`,
		`\t\twidth: ${entry.width},`,
		`\t\theight: ${entry.height},`,
		`\t\tanimated: ${entry.animated},`,
		entry.durationMs === undefined ? null : `\t\tdurationMs: ${entry.durationMs},`,
		`\t\tlight: ${renderMedia(entry.light)},`,
		`\t\tdark: ${renderMedia(entry.dark)},`,
		`\t\tsourceHash: ${literal(entry.sourceHash)},`,
		`\t\tcapturedAt: ${literal(entry.capturedAt)},`,
		`\t\tdevice: ${literal(entry.device)},`,
	].filter((line): line is string => line !== null);

	return `\t${literal(entry.id)}: {\n${lines.join("\n")}\n\t},`;
}

export function renderManifest(
	entries: readonly PreviewEntryJson[],
	byComponent: ReadonlyMap<string, readonly string[]>,
	heroes: ReadonlyMap<string, string>
): string {
	const previews = entries.map(renderEntry).join("\n");

	const grouped = [...byComponent]
		.map(([component, ids]) => `\t${literal(component)}: [${ids.map(literal).join(", ")}],`)
		.join("\n");

	const hero = [...heroes].map(([component, id]) => `\t${literal(component)}: ${literal(id)},`).join("\n");

	return `${HEADER}
export const previews = {
${previews}
} as const satisfies Record<string, PreviewEntry>;

export type PreviewId = keyof typeof previews;

/** Demo ids per component, in the order that component's barrel lists them. */
export const previewsByComponent: Readonly<Record<string, readonly PreviewId[]>> = {
${grouped}
};

/** The one demo per component that fronts its card on the components index. */
export const heroPreviews: Readonly<Record<string, PreviewId>> = {
${hero}
};
`;
}
