import type { IconComponent } from "@delacour/react-native-ui/icon";
import {
	IconArrowExpandVer,
	IconArrowLeftRight,
	IconArrowsRepeatCircle,
	IconAsterisk,
	IconBell,
	IconBold,
	IconBrowserTabs,
	IconBubble2,
	IconBubbleDots,
	IconBulletList,
	IconCalendar1,
	IconChart1,
	IconCheckCircle2,
	IconChevronDoubleRight,
	IconChevronGrabberVertical,
	IconCircleInfo,
	IconCircleRecord,
	IconCursorClick,
	IconDivider,
	IconDotGrid1x3Horizontal,
	IconExclamationTriangle,
	IconFilter1,
	IconFontStyle,
	IconGauge,
	IconHandTouch,
	IconInboxEmpty,
	IconLayersTwo,
	IconLayoutBottomFull,
	IconLayoutLeft,
	IconLayoutTopBottom,
	IconLayoutWindow,
	IconNoteText,
	IconNumberedList,
	IconParagraph,
	IconPeople,
	IconPlaceholder,
	IconPlusLarge,
	IconProgress75,
	IconSettingsSliderHor,
	IconSidebar,
	IconSquareBehindSquare1,
	IconSquareCheck,
	IconSquareCursor,
	IconStar,
	IconStarLines,
	IconTag,
	IconToggle,
	IconTrending4,
	IconWindow,
	IconWindowCursor,
} from "@delacour/react-native-ui/icons/central";
import type { ComponentGroup, ComponentSlug } from "@/components-index";

/**
 * One glyph per screen, keyed by slug so a row added to `components-index.ts`
 * without a glyph here is a type error rather than a blank prefix.
 */
export const COMPONENT_ICONS: Record<ComponentSlug, IconComponent> = {
	accordion: IconChevronGrabberVertical,
	alert: IconExclamationTriangle,
	avatar: IconPeople,
	badge: IconTag,
	"bottom-sheet": IconLayoutBottomFull,
	button: IconSquareCursor,
	calendar: IconCalendar1,
	card: IconLayoutWindow,
	checkbox: IconSquareCheck,
	"empty-state": IconInboxEmpty,
	fab: IconPlusLarge,
	chart: IconChart1,
	collapsible: IconArrowExpandVer,
	"context-menu": IconBubbleDots,
	drawer: IconSidebar,
	dialog: IconWindow,
	feedback: IconBubble2,
	chip: IconFilter1,
	field: IconParagraph,
	icon: IconStar,
	input: IconWindowCursor,
	item: IconLayoutLeft,
	kpi: IconTrending4,
	label: IconAsterisk,
	"list-group": IconBulletList,
	menu: IconDotGrid1x3Horizontal,
	meter: IconGauge,
	popover: IconBubble2,
	pressable: IconCursorClick,
	progress: IconProgress75,
	"progress-button": IconHandTouch,
	radio: IconCircleRecord,
	rating: IconStarLines,
	"selection-mode": IconCheckCircle2,
	separator: IconDivider,
	skeleton: IconPlaceholder,
	"slide-button": IconChevronDoubleRight,
	screen: IconLayoutTopBottom,
	slider: IconSettingsSliderHor,
	spinner: IconArrowsRepeatCircle,
	"stack-card": IconLayersTwo,
	steps: IconNumberedList,
	surface: IconSquareBehindSquare1,
	swipe: IconArrowLeftRight,
	switch: IconToggle,
	tabs: IconBrowserTabs,
	text: IconFontStyle,
	textarea: IconNoteText,
	"toggle-button": IconBold,
	tooltip: IconCircleInfo,
	toast: IconBell,
};

/** One glyph per docs group, for the rows on `/components`. Keyed by name so a new group without one is a type error. */
export const GROUP_ICONS: Record<ComponentGroup, IconComponent> = {
	Actions: IconSquareCursor,
	Forms: IconWindowCursor,
	"Data display": IconChart1,
	Feedback: IconBell,
	Overlays: IconSquareBehindSquare1,
	Navigation: IconBrowserTabs,
	Layout: IconLayoutTopBottom,
	Utilities: IconAsterisk,
};
