/**
 * Regenerates `src/demos/registry.ts` from the demo files on disk.
 *
 * Metro cannot resolve a computed import path, so the map from a demo id to its
 * module has to be written out. `require.context` would do it inside a bundle,
 * but it types every module as `any` — which the house rule forbids, and which
 * would let a malformed `meta` through — and it does not exist outside Metro at
 * all, so the capture script could not read it.
 *
 * The generated file is committed. That is what lets the app build, typecheck
 * and run without anyone having run this first; `demos.test.ts` regenerates in
 * memory and fails if the two have diverged.
 *
 * Usage: bun scripts/gen-demo-registry.ts
 */

import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const DEMOS = join(ROOT, "src/demos");
const OUT = join(DEMOS, "registry.ts");

/** Files that live in `src/demos` but are not demos. */
function isDemoFile(name: string): boolean {
	if (!name.endsWith(".tsx")) return false;
	if (name.includes(".test.")) return false;
	return true;
}

/**
 * Every demo id, as `<component>/<demo>` — or `<component>/<facet>/<demo>` for
 * the components whose galleries split into facets.
 *
 * The id is the directory path plus the filename, so it is also the deep-link's
 * parameters and the media's directory. One string, derived once.
 */
async function collectIds(dir: string): Promise<string[]> {
	const ids: string[] = [];

	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);

		if (entry.isDirectory()) {
			ids.push(...(await collectIds(path)));
			continue;
		}

		if (!isDemoFile(entry.name)) continue;
		ids.push(relative(DEMOS, path).replace(/\.tsx$/, ""));
	}

	return ids;
}

/**
 * A demo id as a JavaScript identifier, for its namespace import.
 *
 * `switch/colours` cannot be an identifier and `switch` is a reserved word, so
 * every id is flattened and prefixed rather than cleverly transformed. The name
 * is never read by a human — only the id is.
 */
function importAlias(id: string): string {
	return `demo_${id.replaceAll(/[^a-zA-Z0-9]/g, "_")}`;
}

/** Every demo id on disk, sorted. Exported so the staleness test walks the same tree. */
export async function demoIds(): Promise<string[]> {
	return (await collectIds(DEMOS)).sort((a, b) => a.localeCompare(b));
}

/**
 * The registry's source text.
 *
 * Exported so `demos.test.ts` can regenerate in memory and compare against the
 * committed file — which is what catches a demo added on a branch where nobody
 * ran the generator.
 */
export function renderRegistry(ids: readonly string[]): string {
	// Sorted by specifier, the way Biome's organizeImports would — so a
	// regenerate is a no-op for the formatter and `bun run check` never has an
	// opinion about a generated file.
	const imports = [
		...ids.map((id) => ({ line: `import * as ${importAlias(id)} from "./${id}";`, specifier: `./${id}` })),
		{ line: `import type { DemoModule } from "./types";`, specifier: "./types" },
	]
		.sort((a, b) => a.specifier.localeCompare(b.specifier))
		.map(({ line }) => line)
		.join("\n");

	const entries = ids.map((id) => `\t"${id}": ${importAlias(id)},`).join("\n");

	return `// Generated by scripts/gen-demo-registry.ts. Do not edit.
//
// Regenerate with \`bun run gen-demos\`, which \`bun dev\` also runs so a demo
// added on a branch cannot reach a device missing from this map.

${imports}

/** Every demo, keyed by the id that is also its deep link and its media path. */
export const DEMOS = {
${entries}
} as const satisfies Record<string, DemoModule>;

export type DemoId = keyof typeof DEMOS;

export const DEMO_IDS = Object.keys(DEMOS) as DemoId[];
`;
}

export const REGISTRY_PATH = OUT;

async function main(): Promise<void> {
	const ids = await demoIds();
	await Bun.write(OUT, renderRegistry(ids));
	console.log(`Generated ${ids.length} demos in src/demos/registry.ts`);
	for (const id of ids) console.log(`  ${id}`);
}

// Only when run directly, so importing this from a test does not rewrite the file.
if (import.meta.main) main();
