// Generated by `bun run gen-skill`. Do not edit.
// Source: registry/registry.json, which is derived from packages/react-native-ui/src.

/** One component, as the registry describes it. */
export type SkillComponent = {
	readonly name: string;
	readonly title: string;
	readonly description: string;
};

export const COMPONENTS: readonly SkillComponent[] = [
	{ name: "accordion", title: "Accordion", description: "Collapsible sections whose panels animate to their measured height." },
	{ name: "badge", title: "Badge", description: "A compact label for status or a count, composed from parts like the button." },
	{ name: "bottom-sheet", title: "Bottom Sheet", description: "A draggable sheet over the screen, on @gorhom/bottom-sheet." },
	{ name: "button", title: "Button", description: "A pressable action composed from parts, with variants, sizes and a loading state." },
	{ name: "chart", title: "Chart", description: "Skia charts on the theme's series ramp: line, area, bar, scatter, candlestick and pie, with grid, axes, legend and tooltip." },
	{ name: "checkbox", title: "Checkbox", description: "A checkbox with an indeterminate state, and a group that owns the selection." },
	{ name: "field", title: "Field", description: "One control with its label, description and error — and the state they all read." },
	{ name: "icon", title: "Icon", description: "A Central Icons glyph that inherits size and colour from the surrounding component." },
	{ name: "input", title: "Input", description: "A text field, with a group that puts a prefix or suffix inside its border." },
	{ name: "list-group", title: "List Group", description: "A surface grouping related rows, with dividers inserted automatically." },
	{ name: "pressable", title: "Pressable", description: "The Gesture API press primitive: scale and fade feedback, haptics, disabled and busy states." },
	{ name: "progress", title: "Progress", description: "A bar showing how far a task has got, or a looping segment while it is under way." },
	{ name: "provider", title: "Provider", description: "The root provider: safe-area insets seeded from the launch snapshot, and gesture handling." },
	{ name: "radio", title: "Radio", description: "A radio and the group that owns which one is selected." },
	{ name: "screen", title: "Screen", description: "A screen frame: pinned chrome, a content region, and whatever scrolls between them." },
	{ name: "separator", title: "Separator", description: "A one-pixel rule, hidden from assistive technology." },
	{ name: "slider", title: "Slider", description: "A value along a track, dragged by a handle that follows the gesture." },
	{ name: "spinner", title: "Spinner", description: "An animated loading indicator drawn on the icon scale." },
	{ name: "switch", title: "Switch", description: "An on/off control whose thumb can be dragged as well as tapped." },
	{ name: "tabs", title: "Tabs", description: "A swipeable pager with an indicator measured against the active tab." },
	{ name: "text", title: "Text", description: "Typography: the type scale, weights and the page-level colours." },
];
