/**
 * The generator's one pure function, so a test can hold the committed file
 * equal to a fresh render without shelling out to the script.
 */

export type RegistryEntry = {
	name: string;
	type: string;
	title: string;
	description: string;
};

/** Components only. The utilities an item pulls in are not things to offer. */
export function componentEntries(items: readonly RegistryEntry[]): RegistryEntry[] {
	return items.filter((item) => item.type === "registry:ui").sort((a, b) => a.name.localeCompare(b.name));
}

export function renderComponents(items: readonly RegistryEntry[]): string {
	const rows = componentEntries(items).map(
		(item) => `\t{ name: ${json(item.name)}, title: ${json(item.title)}, description: ${json(item.description)} },`
	);

	return [
		"// Generated by `bun run gen-skill`. Do not edit.",
		"// Source: registry/registry.json, which is derived from packages/native-ui/src.",
		"",
		"/** One component, as the registry describes it. */",
		"export type SkillComponent = {",
		"\treadonly name: string;",
		"\treadonly title: string;",
		"\treadonly description: string;",
		"};",
		"",
		"export const COMPONENTS: readonly SkillComponent[] = [",
		...rows,
		"];",
		"",
	].join("\n");
}

function json(value: string): string {
	return JSON.stringify(value);
}
