// Generated by scripts/gen-demo-registry.ts. Do not edit.
//
// Regenerate with `bun run gen-demos`, which `bun dev` also runs so a demo
// added on a branch cannot reach a device missing from this map.

import * as demo_accordion_a_glyph_beside_the_title from "./accordion/a-glyph-beside-the-title";
import * as demo_accordion_any_number_at_once from "./accordion/any-number-at-once";
import * as demo_accordion_disabled from "./accordion/disabled";
import * as demo_accordion_one_at_a_time from "./accordion/one-at-a-time";
import * as demo_accordion_sizes from "./accordion/sizes";
import * as demo_accordion_variants from "./accordion/variants";
import * as demo_badge_composed_icon from "./badge/composed-icon";
import * as demo_badge_dismissible from "./badge/dismissible";
import * as demo_badge_sizes from "./badge/sizes";
import * as demo_badge_status_dot from "./badge/status-dot";
import * as demo_badge_variants_and_colours from "./badge/variants-and-colours";
import * as demo_bottom_sheet_anatomy_a_scrim_that_does_not_dismiss from "./bottom-sheet/anatomy/a-scrim-that-does-not-dismiss";
import * as demo_bottom_sheet_anatomy_the_whole_composition from "./bottom-sheet/anatomy/the-whole-composition";
import * as demo_bottom_sheet_anatomy_uncontrolled from "./bottom-sheet/anatomy/uncontrolled";
import * as demo_bottom_sheet_footer_inline_in_the_flow from "./bottom-sheet/footer/inline-in-the-flow";
import * as demo_bottom_sheet_footer_on_a_short_sheet_sticky_still_pins from "./bottom-sheet/footer/on-a-short-sheet-sticky-still-pins";
import * as demo_bottom_sheet_footer_sticky_pinned_to_the_sheet from "./bottom-sheet/footer/sticky-pinned-to-the-sheet";
import * as demo_bottom_sheet_form_a_form_in_a_sheet from "./bottom-sheet/form/a-form-in-a-sheet";
import * as demo_bottom_sheet_scrolling_a_scrolling_sheet from "./bottom-sheet/scrolling/a-scrolling-sheet";
import * as demo_bottom_sheet_scrolling_scrolling_under_a_pinned_footer from "./bottom-sheet/scrolling/scrolling-under-a-pinned-footer";
import * as demo_bottom_sheet_sizing_dynamic_but_capped from "./bottom-sheet/sizing/dynamic-but-capped";
import * as demo_bottom_sheet_sizing_explicit_snap_points from "./bottom-sheet/sizing/explicit-snap-points";
import * as demo_bottom_sheet_sizing_sized_to_its_content from "./bottom-sheet/sizing/sized-to-its-content";
import * as demo_bottom_sheet_sizing_the_same_sheet_more_content from "./bottom-sheet/sizing/the-same-sheet-more-content";
import * as demo_button_disabled from "./button/disabled";
import * as demo_button_group from "./button/group";
import * as demo_button_group_input from "./button/group-input";
import * as demo_button_group_orientation from "./button/group-orientation";
import * as demo_button_group_separator from "./button/group-separator";
import * as demo_button_group_text from "./button/group-text";
import * as demo_button_icon_button from "./button/icon-button";
import * as demo_button_icons from "./button/icons";
import * as demo_button_loading from "./button/loading";
import * as demo_button_sizes from "./button/sizes";
import * as demo_button_variants from "./button/variants";
import * as demo_chart_area from "./chart/area";
import * as demo_chart_colours from "./chart/colours";
import * as demo_chart_curves from "./chart/curves";
import * as demo_chart_dashboard from "./chart/dashboard";
import * as demo_chart_empty from "./chart/empty";
import * as demo_chart_grid_and_axes from "./chart/grid-and-axes";
import * as demo_chart_legend from "./chart/legend";
import * as demo_chart_line from "./chart/line";
import * as demo_chart_multi_series from "./chart/multi-series";
import * as demo_chart_sizes from "./chart/sizes";
import * as demo_chart_time_series from "./chart/time-series";
import * as demo_chart_tooltip from "./chart/tooltip";
import * as demo_checkbox_alignment from "./checkbox/alignment";
import * as demo_checkbox_checkbox_group from "./checkbox/checkbox-group";
import * as demo_checkbox_colours from "./checkbox/colours";
import * as demo_checkbox_indeterminate from "./checkbox/indeterminate";
import * as demo_checkbox_invalid_and_disabled from "./checkbox/invalid-and-disabled";
import * as demo_checkbox_sizes from "./checkbox/sizes";
import * as demo_field_anatomy_all_four from "./field/anatomy/all-four";
import * as demo_field_anatomy_label_and_control from "./field/anatomy/label-and-control";
import * as demo_field_anatomy_the_gap_ladder from "./field/anatomy/the-gap-ladder";
import * as demo_field_anatomy_with_a_description from "./field/anatomy/with-a-description";
import * as demo_field_anatomy_with_an_error from "./field/anatomy/with-an-error";
import * as demo_field_form_in_a_form from "./field/form/in-a-form";
import * as demo_field_grouping_a_nested_set from "./field/grouping/a-nested-set";
import * as demo_field_grouping_group from "./field/grouping/group";
import * as demo_field_grouping_separator from "./field/grouping/separator";
import * as demo_field_grouping_separator_on_a_card from "./field/grouping/separator-on-a-card";
import * as demo_field_grouping_set_and_legend from "./field/grouping/set-and-legend";
import * as demo_field_orientation_horizontal from "./field/orientation/horizontal";
import * as demo_field_orientation_horizontal_and_disabled from "./field/orientation/horizontal-and-disabled";
import * as demo_field_orientation_horizontal_and_invalid from "./field/orientation/horizontal-and-invalid";
import * as demo_field_orientation_horizontal_with_a_description from "./field/orientation/horizontal-with-a-description";
import * as demo_field_orientation_vertical from "./field/orientation/vertical";
import * as demo_field_states_a_control_can_opt_out from "./field/states/a-control-can-opt-out";
import * as demo_field_states_disabled from "./field/states/disabled";
import * as demo_field_states_live from "./field/states/live";
import * as demo_field_states_one_flag_three_things from "./field/states/one-flag-three-things";
import * as demo_field_states_through_an_input_group from "./field/states/through-an-input-group";
import * as demo_icon_colour_is_a_token from "./icon/colour-is-a-token";
import * as demo_icon_inherited_from_a_button from "./icon/inherited-from-a-button";
import * as demo_icon_the_size_scale from "./icon/the-size-scale";
import * as demo_input_colors_caret_and_selection from "./input/colors/caret-and-selection";
import * as demo_input_colors_defaults from "./input/colors/defaults";
import * as demo_input_colors_invalid_wins_by_default from "./input/colors/invalid-wins-by-default";
import * as demo_input_colors_placeholder from "./input/colors/placeholder";
import * as demo_input_form_in_a_form from "./input/form/in-a-form";
import * as demo_input_group_controls from "./input/group/controls";
import * as demo_input_group_icons from "./input/group/icons";
import * as demo_input_group_multiline from "./input/group/multiline";
import * as demo_input_group_side_by_side from "./input/group/side-by-side";
import * as demo_input_group_sizes_and_states from "./input/group/sizes-and-states";
import * as demo_input_group_text_affixes from "./input/group/text-affixes";
import * as demo_input_sizes_beside_a_button from "./input/sizes/beside-a-button";
import * as demo_input_sizes_multiline from "./input/sizes/multiline";
import * as demo_input_sizes_sizes from "./input/sizes/sizes";
import * as demo_input_states_keyboards from "./input/states/keyboards";
import * as demo_input_states_live_validation from "./input/states/live-validation";
import * as demo_input_states_not_editable from "./input/states/not-editable";
import * as demo_input_states_secure from "./input/states/secure";
import * as demo_input_variants_at_rest from "./input/variants/at-rest";
import * as demo_input_variants_disabled from "./input/variants/disabled";
import * as demo_input_variants_focused from "./input/variants/focused";
import * as demo_input_variants_invalid from "./input/variants/invalid";
import * as demo_list_group_custom_suffix from "./list-group/custom-suffix";
import * as demo_list_group_dividers from "./list-group/dividers";
import * as demo_list_group_sizes from "./list-group/sizes";
import * as demo_list_group_variants from "./list-group/variants";
import * as demo_pressable_as_child from "./pressable/as-child";
import * as demo_pressable_disabled_and_busy from "./pressable/disabled-and-busy";
import * as demo_pressable_haptics from "./pressable/haptics";
import * as demo_pressable_named_feedback from "./pressable/named-feedback";
import * as demo_radio_custom_indicator from "./radio/custom-indicator";
import * as demo_radio_horizontal_wrapping from "./radio/horizontal-wrapping";
import * as demo_radio_per_option_description from "./radio/per-option-description";
import * as demo_radio_sizes from "./radio/sizes";
import * as demo_radio_variants_and_states from "./radio/variants-and-states";
import * as demo_screen_a_pushed_screen from "./screen/a-pushed-screen";
import * as demo_screen_anatomy from "./screen/anatomy";
import * as demo_screen_loading_and_error from "./screen/loading-and-error";
import * as demo_separator_inside_a_list_group from "./separator/inside-a-list-group";
import * as demo_separator_orientations from "./separator/orientations";
import * as demo_separator_weight_and_colour from "./separator/weight-and-colour";
import * as demo_slider_a_range from "./slider/a-range";
import * as demo_slider_anatomy from "./slider/anatomy";
import * as demo_slider_colours from "./slider/colours";
import * as demo_slider_disabled_and_invalid from "./slider/disabled-and-invalid";
import * as demo_slider_sizes from "./slider/sizes";
import * as demo_slider_vertical from "./slider/vertical";
import * as demo_spinner_colours from "./spinner/colours";
import * as demo_spinner_custom_glyph from "./spinner/custom-glyph";
import * as demo_spinner_sizes from "./spinner/sizes";
import * as demo_switch_colours from "./switch/colours";
import * as demo_switch_disabled_and_invalid from "./switch/disabled-and-invalid";
import * as demo_switch_sizes from "./switch/sizes";
import * as demo_switch_start_and_end_content from "./switch/start-and-end-content";
import * as demo_switch_tap_or_drag from "./switch/tap-or-drag";
import * as demo_tabs_composition_a_restyled_indicator_and_a_disabled_tab from "./tabs/composition/a-restyled-indicator-and-a-disabled-tab";
import * as demo_tabs_composition_a_scroller_inside_a_panel from "./tabs/composition/a-scroller-inside-a-panel";
import * as demo_tabs_composition_composed_icons_and_a_render_prop from "./tabs/composition/composed-icons-and-a-render-prop";
import * as demo_tabs_composition_separators from "./tabs/composition/separators";
import * as demo_tabs_scrolling_fewer_tabs_than_room from "./tabs/scrolling/fewer-tabs-than-room";
import * as demo_tabs_scrolling_twelve_tabs from "./tabs/scrolling/twelve-tabs";
import * as demo_tabs_sizes_every_size from "./tabs/sizes/every-size";
import * as demo_tabs_swipe_a_tab_inserted_before_the_active_one from "./tabs/swipe/a-tab-inserted-before-the-active-one";
import * as demo_tabs_swipe_controlled_rejecting_every_third_change from "./tabs/swipe/controlled-rejecting-every-third-change";
import * as demo_tabs_swipe_is_swipeable_false from "./tabs/swipe/is-swipeable-false";
import * as demo_tabs_swipe_swipeable_the_default from "./tabs/swipe/swipeable-the-default";
import * as demo_tabs_variants_every_variant from "./tabs/variants/every-variant";
import * as demo_text_alignment from "./text/alignment";
import * as demo_text_colour from "./text/colour";
import * as demo_text_inline_presets from "./text/inline-presets";
import * as demo_text_size from "./text/size";
import * as demo_text_type_scale from "./text/type-scale";
import * as demo_text_weight from "./text/weight";
import type { DemoModule } from "./types";

/** Every demo, keyed by the id that is also its deep link and its media path. */
export const DEMOS = {
	"accordion/a-glyph-beside-the-title": demo_accordion_a_glyph_beside_the_title,
	"accordion/any-number-at-once": demo_accordion_any_number_at_once,
	"accordion/disabled": demo_accordion_disabled,
	"accordion/one-at-a-time": demo_accordion_one_at_a_time,
	"accordion/sizes": demo_accordion_sizes,
	"accordion/variants": demo_accordion_variants,
	"badge/composed-icon": demo_badge_composed_icon,
	"badge/dismissible": demo_badge_dismissible,
	"badge/sizes": demo_badge_sizes,
	"badge/status-dot": demo_badge_status_dot,
	"badge/variants-and-colours": demo_badge_variants_and_colours,
	"bottom-sheet/anatomy/a-scrim-that-does-not-dismiss": demo_bottom_sheet_anatomy_a_scrim_that_does_not_dismiss,
	"bottom-sheet/anatomy/the-whole-composition": demo_bottom_sheet_anatomy_the_whole_composition,
	"bottom-sheet/anatomy/uncontrolled": demo_bottom_sheet_anatomy_uncontrolled,
	"bottom-sheet/footer/inline-in-the-flow": demo_bottom_sheet_footer_inline_in_the_flow,
	"bottom-sheet/footer/on-a-short-sheet-sticky-still-pins": demo_bottom_sheet_footer_on_a_short_sheet_sticky_still_pins,
	"bottom-sheet/footer/sticky-pinned-to-the-sheet": demo_bottom_sheet_footer_sticky_pinned_to_the_sheet,
	"bottom-sheet/form/a-form-in-a-sheet": demo_bottom_sheet_form_a_form_in_a_sheet,
	"bottom-sheet/scrolling/a-scrolling-sheet": demo_bottom_sheet_scrolling_a_scrolling_sheet,
	"bottom-sheet/scrolling/scrolling-under-a-pinned-footer": demo_bottom_sheet_scrolling_scrolling_under_a_pinned_footer,
	"bottom-sheet/sizing/dynamic-but-capped": demo_bottom_sheet_sizing_dynamic_but_capped,
	"bottom-sheet/sizing/explicit-snap-points": demo_bottom_sheet_sizing_explicit_snap_points,
	"bottom-sheet/sizing/sized-to-its-content": demo_bottom_sheet_sizing_sized_to_its_content,
	"bottom-sheet/sizing/the-same-sheet-more-content": demo_bottom_sheet_sizing_the_same_sheet_more_content,
	"button/disabled": demo_button_disabled,
	"button/group": demo_button_group,
	"button/group-input": demo_button_group_input,
	"button/group-orientation": demo_button_group_orientation,
	"button/group-separator": demo_button_group_separator,
	"button/group-text": demo_button_group_text,
	"button/icon-button": demo_button_icon_button,
	"button/icons": demo_button_icons,
	"button/loading": demo_button_loading,
	"button/sizes": demo_button_sizes,
	"button/variants": demo_button_variants,
	"chart/area": demo_chart_area,
	"chart/colours": demo_chart_colours,
	"chart/curves": demo_chart_curves,
	"chart/dashboard": demo_chart_dashboard,
	"chart/empty": demo_chart_empty,
	"chart/grid-and-axes": demo_chart_grid_and_axes,
	"chart/legend": demo_chart_legend,
	"chart/line": demo_chart_line,
	"chart/multi-series": demo_chart_multi_series,
	"chart/sizes": demo_chart_sizes,
	"chart/time-series": demo_chart_time_series,
	"chart/tooltip": demo_chart_tooltip,
	"checkbox/alignment": demo_checkbox_alignment,
	"checkbox/checkbox-group": demo_checkbox_checkbox_group,
	"checkbox/colours": demo_checkbox_colours,
	"checkbox/indeterminate": demo_checkbox_indeterminate,
	"checkbox/invalid-and-disabled": demo_checkbox_invalid_and_disabled,
	"checkbox/sizes": demo_checkbox_sizes,
	"field/anatomy/all-four": demo_field_anatomy_all_four,
	"field/anatomy/label-and-control": demo_field_anatomy_label_and_control,
	"field/anatomy/the-gap-ladder": demo_field_anatomy_the_gap_ladder,
	"field/anatomy/with-a-description": demo_field_anatomy_with_a_description,
	"field/anatomy/with-an-error": demo_field_anatomy_with_an_error,
	"field/form/in-a-form": demo_field_form_in_a_form,
	"field/grouping/a-nested-set": demo_field_grouping_a_nested_set,
	"field/grouping/group": demo_field_grouping_group,
	"field/grouping/separator": demo_field_grouping_separator,
	"field/grouping/separator-on-a-card": demo_field_grouping_separator_on_a_card,
	"field/grouping/set-and-legend": demo_field_grouping_set_and_legend,
	"field/orientation/horizontal": demo_field_orientation_horizontal,
	"field/orientation/horizontal-and-disabled": demo_field_orientation_horizontal_and_disabled,
	"field/orientation/horizontal-and-invalid": demo_field_orientation_horizontal_and_invalid,
	"field/orientation/horizontal-with-a-description": demo_field_orientation_horizontal_with_a_description,
	"field/orientation/vertical": demo_field_orientation_vertical,
	"field/states/a-control-can-opt-out": demo_field_states_a_control_can_opt_out,
	"field/states/disabled": demo_field_states_disabled,
	"field/states/live": demo_field_states_live,
	"field/states/one-flag-three-things": demo_field_states_one_flag_three_things,
	"field/states/through-an-input-group": demo_field_states_through_an_input_group,
	"icon/colour-is-a-token": demo_icon_colour_is_a_token,
	"icon/inherited-from-a-button": demo_icon_inherited_from_a_button,
	"icon/the-size-scale": demo_icon_the_size_scale,
	"input/colors/caret-and-selection": demo_input_colors_caret_and_selection,
	"input/colors/defaults": demo_input_colors_defaults,
	"input/colors/invalid-wins-by-default": demo_input_colors_invalid_wins_by_default,
	"input/colors/placeholder": demo_input_colors_placeholder,
	"input/form/in-a-form": demo_input_form_in_a_form,
	"input/group/controls": demo_input_group_controls,
	"input/group/icons": demo_input_group_icons,
	"input/group/multiline": demo_input_group_multiline,
	"input/group/side-by-side": demo_input_group_side_by_side,
	"input/group/sizes-and-states": demo_input_group_sizes_and_states,
	"input/group/text-affixes": demo_input_group_text_affixes,
	"input/sizes/beside-a-button": demo_input_sizes_beside_a_button,
	"input/sizes/multiline": demo_input_sizes_multiline,
	"input/sizes/sizes": demo_input_sizes_sizes,
	"input/states/keyboards": demo_input_states_keyboards,
	"input/states/live-validation": demo_input_states_live_validation,
	"input/states/not-editable": demo_input_states_not_editable,
	"input/states/secure": demo_input_states_secure,
	"input/variants/at-rest": demo_input_variants_at_rest,
	"input/variants/disabled": demo_input_variants_disabled,
	"input/variants/focused": demo_input_variants_focused,
	"input/variants/invalid": demo_input_variants_invalid,
	"list-group/custom-suffix": demo_list_group_custom_suffix,
	"list-group/dividers": demo_list_group_dividers,
	"list-group/sizes": demo_list_group_sizes,
	"list-group/variants": demo_list_group_variants,
	"pressable/as-child": demo_pressable_as_child,
	"pressable/disabled-and-busy": demo_pressable_disabled_and_busy,
	"pressable/haptics": demo_pressable_haptics,
	"pressable/named-feedback": demo_pressable_named_feedback,
	"radio/custom-indicator": demo_radio_custom_indicator,
	"radio/horizontal-wrapping": demo_radio_horizontal_wrapping,
	"radio/per-option-description": demo_radio_per_option_description,
	"radio/sizes": demo_radio_sizes,
	"radio/variants-and-states": demo_radio_variants_and_states,
	"screen/a-pushed-screen": demo_screen_a_pushed_screen,
	"screen/anatomy": demo_screen_anatomy,
	"screen/loading-and-error": demo_screen_loading_and_error,
	"separator/inside-a-list-group": demo_separator_inside_a_list_group,
	"separator/orientations": demo_separator_orientations,
	"separator/weight-and-colour": demo_separator_weight_and_colour,
	"slider/a-range": demo_slider_a_range,
	"slider/anatomy": demo_slider_anatomy,
	"slider/colours": demo_slider_colours,
	"slider/disabled-and-invalid": demo_slider_disabled_and_invalid,
	"slider/sizes": demo_slider_sizes,
	"slider/vertical": demo_slider_vertical,
	"spinner/colours": demo_spinner_colours,
	"spinner/custom-glyph": demo_spinner_custom_glyph,
	"spinner/sizes": demo_spinner_sizes,
	"switch/colours": demo_switch_colours,
	"switch/disabled-and-invalid": demo_switch_disabled_and_invalid,
	"switch/sizes": demo_switch_sizes,
	"switch/start-and-end-content": demo_switch_start_and_end_content,
	"switch/tap-or-drag": demo_switch_tap_or_drag,
	"tabs/composition/a-restyled-indicator-and-a-disabled-tab": demo_tabs_composition_a_restyled_indicator_and_a_disabled_tab,
	"tabs/composition/a-scroller-inside-a-panel": demo_tabs_composition_a_scroller_inside_a_panel,
	"tabs/composition/composed-icons-and-a-render-prop": demo_tabs_composition_composed_icons_and_a_render_prop,
	"tabs/composition/separators": demo_tabs_composition_separators,
	"tabs/scrolling/fewer-tabs-than-room": demo_tabs_scrolling_fewer_tabs_than_room,
	"tabs/scrolling/twelve-tabs": demo_tabs_scrolling_twelve_tabs,
	"tabs/sizes/every-size": demo_tabs_sizes_every_size,
	"tabs/swipe/a-tab-inserted-before-the-active-one": demo_tabs_swipe_a_tab_inserted_before_the_active_one,
	"tabs/swipe/controlled-rejecting-every-third-change": demo_tabs_swipe_controlled_rejecting_every_third_change,
	"tabs/swipe/is-swipeable-false": demo_tabs_swipe_is_swipeable_false,
	"tabs/swipe/swipeable-the-default": demo_tabs_swipe_swipeable_the_default,
	"tabs/variants/every-variant": demo_tabs_variants_every_variant,
	"text/alignment": demo_text_alignment,
	"text/colour": demo_text_colour,
	"text/inline-presets": demo_text_inline_presets,
	"text/size": demo_text_size,
	"text/type-scale": demo_text_type_scale,
	"text/weight": demo_text_weight,
} as const satisfies Record<string, DemoModule>;

export type DemoId = keyof typeof DEMOS;

export const DEMO_IDS = Object.keys(DEMOS) as DemoId[];
