// Generated by apps/web/scripts/gen-theme.ts from HOUSE_CONFIG. Do not edit.
//
// The house page backgrounds as sRGB hex — `--color-fd-background` in each
// mode, for the two places that cannot read `oklch()`: the `theme-color`
// metas and the web manifest. Regenerate with `bun run gen-theme`.

/** The house preset's page background, light and dark, as `#rrggbb`. */
export const HOUSE_BACKGROUND = {
	light: "#fafafa",
	dark: "#09090b",
} as const;
